spring.application.name=Follow_3

graphhopper.osm-file=korea-latest.osm.pbf
graphhopper.graph-dir=graph-cache
graphhopper.vehicle=bike
graphhopper.profile=bike

#graphhopper.datareader.file=./south-korea-latest.osm.pbf
#graphhopper.graph.location=./graphhopper
#graphhopper.routing.algorithm=dijkstra
#graphhopper.prepare.ch.weightings=no
#graphhopper.prepare.lm.weightings=no
